title: Benchmark results
description: A Convexification-Based Outer-Approximation Method for Convex and Nonconvex MINLP
show_downloads: false
google_analytics:
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme